In [2]:
import pandas as pd
import numpy as np

In [3]:
one_d_array = np.array([1,3])
print(one_d_array)

[1 3]


In [12]:
# Range
range_array = np.arange(1, 20, 5)
# Can also specify how many ints in array (starts at 0)
solo_range_array = np.arange(0, 4)

print(range_array)
print(solo_range_array)

[ 1  6 11 16]
[0 1 2 3]


In [ ]:
lin_space = np.linspace(1, 100, 5, dtype=int) # float by default
print(lin_space)

[  1  25  50  75 100]


In [22]:
ones = np.ones(3)
zeros = np.zeros(3)
empty = np.empty(3)
random = np.random.rand(3)

print(ones)
print(zeros)
print(empty)
print(random)

[1. 1. 1.]
[0. 0. 0.]
[0. 0. 0.]
[0.63035516 0.02528664 0.39455587]


In [27]:
# Multidemensional arrays
# comma separated arrays
two_d_array = np.array([[1,2,3], [4,5,6]])

# can also dump it and shape it
preshape = np.array([1,2,3,4,5,6])
reshape = np.reshape(preshape, (2,3)) #passing the array to shape and dimensions

print(two_d_array)
print(reshape)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# find number of dimension
print(reshape.ndim)

#find the shape
print(reshape.shape)

# find size (total number)
print(reshape.size)

2
(2, 3)
6


In [33]:
a = np.array([1,2,3,4,5])

print(a[:])

sliced_two_rows = reshape[0:2] # first 2 rows
print(sliced_two_rows)

sliced_cols = reshape[:,1]
print(sliced_cols)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[2 5]


In [41]:
# Stacking
a1 = np.array([[1,1], [2,2]])
a2 = np.array([[3,3], [4,4]])

vert = np.vstack((a1, a2))
print(vert)

hor = np.hstack((a1, a2))
print(hor)

split = np.hsplit(hor,2)
print(split)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]
